services:
 sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: build-hub-sql-server
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    ports:
      - "${MSSQL_PORT}"
    volumes:
      - sqlserverdata:/var/opt/mssql
 seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
     ACCEPT_EULA: "Y"
     SEQ_PASSWORD: "${SEQ_PASSWORD}"
    ports:
     - "${SEQ_PORT}"

volumes:
  sqlserverdata:
