<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RootNamespace>BuildHub.Domain</RootNamespace>
	<AssemblyName>BuildHub.Domain</AssemblyName>
	<BaseOutputPath>..\bin\Domain</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\Common.csproj" />
    <ProjectReference Include="..\DataEngine\DataEngine.csproj" />
  </ItemGroup>

</Project>
