CREATE TABLE REFRESH_TOKENS
(
	ID				INT						 NOT NULL IDENTITY(1,1),
	[GUID]			UNIQUEIDENTIFIER		 NOT NULL,
	[VERSION]		INT						 NOT NULL,
	CREATED_AT		DATETIME2				 NOT NULL,
	UPDATED_AT		DATETIME2				 NOT NULL,
	USER_ID			INT						 NOT NULL,
	REFRESH_TOKEN	VARCHAR(128)			 NOT NULL,
	EXPIRATION_DATE	DATETIME2				 NOT NULL,
	IS_REVOKED		BIT						 NOT NULL

	CONSTRAINT PK_REFRESH_TOKENS_ID PRIMARY KEY (ID),
	CONSTRAINT FK_REFRESH_TOKENS_USER_ID FOREIGN KEY(USER_ID)
	REFERENCES USERS(ID)
)
GO

CREATE UNIQUE NONCLUSTERED INDEX UX_REFRESH_TOKENS_GUID
	ON REFRESH_TOKENS
(
	GUID
)
GO

CREATE UNIQUE NONCLUSTERED INDEX UX_REFRESH_TOKENS_USER_ID
	ON REFRESH_TOKENS
(
	USER_ID
)
GO
