CREATE TABLE USERS
(
	ID						INT					NOT NULL IDENTITY(1,1),
	[GUID]					UNIQUEIDENTIFIER	NOT NULL,
	[VERSION]				INT					NOT NULL,
	CREATED_AT				DATETIME2			NOT NULL,
	UPDATED_AT				DATETIME2			NOT NULL,
	FIRST_NAME				NVARCHAR(128)		NOT NULL,
	LAST_NAME				NVARCHAR(128)		NOT NULL,
	EMAIL					NVARCHAR(254)		NOT NULL,
	[USER_NAME]				NVARCHAR(32)		NOT NULL,
	FAILED_LOGIN_ATTEMPTS   INT					NOT NULL,

	CONSTRAINT PK_USERS_ID	PRIMARY KEY(Id)
 )
GO

CREATE UNIQUE NONCLUSTERED INDEX UX_USERS_GUID
	ON USERS
(
	GUID
)
GO

CREATE UNIQUE NONCLUSTERED INDEX UX_USERS_EMAIL
	ON USERS
(
	EMAIL
)
GO

CREATE UNIQUE NONCLUSTERED INDEX UX_USERS_USER_NAME
	ON USERS
(
	[USER_NAME]
)
GO
