CREATE TABLE USER_CREDENTIALS
(
	ID				INT					 NOT NULL IDENTITY(1,1),
	[GUID]			UNIQUEIDENTIFIER	 NOT NULL,
	[VERSION]		INT					 NOT NULL,
	CREATED_AT		DATETIME			 NOT NULL,
	UPDATED_AT		DATETIME			 NOT NULL,
	USER_ID			INT					 NOT NULL,
	HASHED_PASSWORD VARCHAR(128)		 NOT NULL,

	CONSTRAINT PK_USER_CREDENTIALS_ID PRIMARY KEY (ID),
	CONSTRAINT FK_USER_CREDENTIALS_USER_ID FOREIGN KEY(USER_ID)
		REFERENCES USERS(ID)
	ON DELETE CASCADE
)
GO

CREATE UNIQUE NONCLUSTERED INDEX UX_USER_CREDENTIALS_GUID
	ON USER_CREDENTIALS
(
	GUID
)
GO

CREATE UNIQUE NONCLUSTERED INDEX UX_USER_CREDENTIALS_USER_ID
	ON USER_CREDENTIALS
(
	USER_ID
)
GO
