using BuildHub.CommandBuilder.Models.Execution;

namespace BuildHub.CommandBuilder.Models;

/// <summary>
/// Represents the result of generating or executing a build command.
/// Contains information about success, the generated command, working directory,
/// and any error messages encountered during the process.
/// </summary>
public sealed class BuildCommandResult
{
	/// <summary>
	/// Indicates whether the build command was successfully generated and validated.
	/// </summary>
	public bool Success { get; }

	/// <summary>
	/// Gets the name of the command builder that produced this result.
	/// </summary>
	public string BuilderName { get; }

	/// <summary>
	/// Any error message encountered during command generation or validation.
	/// Empty if <see cref="Success"/> is true.
	/// </summary>
	public string ErrorMessage { get; }

	/// <summary>
	/// The duration it took to generate or execute the build command.
	/// </summary>
	/// <remarks>
	/// Typically measured from the start of command execution to completion.
	/// This property is meaningful when the build process is timed and can help
	/// track performance or diagnose slow builds.
	/// </remarks>
	public TimeSpan BuildTime { get; set; }

	/// <summary>
	/// Steps generated by this builder.
	/// </summary>
	public IReadOnlyList<ExecutionStep> Steps { get; }

	/// <summary>
	/// Initializes a new instance of <see cref="BuildCommandResult"/>.
	/// </summary>
	/// <param name="success">Indicates whether the build command was successful.</param>
	/// <param name="errorMessage">Any error message; empty if <paramref name="success"/> is true.</param>
	private BuildCommandResult(
	bool success,
	string builderName,
	IReadOnlyList<ExecutionStep> steps,
	TimeSpan buildTime,
	string? errorMessage)
	{
		Success = success;
		BuilderName = builderName;
		Steps = steps;
		BuildTime = buildTime;
		ErrorMessage = errorMessage ?? string.Empty;
	}

	/// <summary>
	/// Creates a successful <see cref="BuildCommandResult"/> for a single command.
	/// </summary>
	/// <param name="builderName">The name of the command builder.</param>
	/// <param name="steps">The steps generated by this builder.</param>
	/// <param name="buildTime">The time taken to generate or execute the command.</param>
	/// <returns>A successful <see cref="BuildCommandResult"/>.</returns>
	public static BuildCommandResult CreateSuccess(
		string builderName,
		TimeSpan buildTime,
		IReadOnlyList<ExecutionStep> steps)
		=> new(true, builderName, steps, buildTime, null);


	/// <summary>
	/// Creates a failed <see cref="BuildCommandResult"/> for a single command.
	/// </summary>
	/// <param name="errorMessage">The error message describing the failure.</param>
	/// <param name="buildTime">The time taken before the failure occurred.</param>
	/// <param name="builderName">The name of the command builder.</param>
	/// <returns>A failed <see cref="BuildCommandResult"/>.</returns>
	public static BuildCommandResult CreateFailure(
		string builderName,
		TimeSpan buildTime,
		string errorMessage)
		=> new(false, builderName, Array.Empty<ExecutionStep>(), buildTime, errorMessage);

	/// <inheritdoc />
	public override string ToString()
	{
		var commandResult = new List<string>
		{
			$"Success: {Success}",
			$"BuilderName: \"{BuilderName ?? "<null>"}\"",
			"Steps:"
		};

		if (Steps is null || Steps.Count == 0)
		{
			commandResult.Add("\t<none>");
		}
		else
		{
			foreach (var step in Steps)
			{
				commandResult.Add($"\t[{step.Id}] Order: {step.Order} Name: {step.Name}");

				if (step.RetryPolicy != null || step.TimeoutPolicy != null)
					commandResult.Add($"\t\t{step.RetryPolicy} {step.TimeoutPolicy}");

				if (step.DependsOn.Count > 0)
					commandResult.Add($"\t\tDepends on: {string.Join(", ", step.DependsOn)}");

				commandResult.Add($"\t\tCommands:");
				foreach (var command in step.Commands)
				{
					commandResult.Add($"\t\t\t Executable: {command.Executable} Arguments: {command.Arguments} Working dir: {command.WorkingDirectory ?? string.Empty}");
				}
			}
		}

		commandResult.Add($"BuildTime: {BuildTime.TotalSeconds:0.###} s {BuildTime.TotalMilliseconds:0.####} ms ({BuildTime.Ticks} ticks)");

		if (!string.IsNullOrEmpty(ErrorMessage) || !string.IsNullOrWhiteSpace(ErrorMessage))
			commandResult.Add($"ErrorMessage: \"{ErrorMessage}\"");

		return string.Join("\n", commandResult);
	}
}
