<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<AssemblyName>BuildHub.Infrastructure</AssemblyName>
	<RootNamespace>BuildHub.Infrastructure</RootNamespace>
	<BaseOutputPath>..\bin\Infrastructure</BaseOutputPath>
  </PropertyGroup>

</Project>
