CREATE TABLE CONCURRENCY_TESTS
(
	ID INT  NOT NULL IDENTITY(1,1),
	GUID			UNIQUEIDENTIFIER				  NOT NULL,
	VERSION			INT								  NOT NULL,
	CREATED_AT		DATETIME						  NOT NULL,
	UPDATED_AT		DATETIME						  NOT NULL,
	NAME			VARCHAR(128)					  NOT NULL,
	CONSTRAINT PK_CONCURRENCY_TESTS PRIMARY KEY NONCLUSTERED (GUID)
)
GO

CREATE UNIQUE CLUSTERED INDEX UX_CONCURRENCY_TESTS_ID
ON CONCURRENCY_TESTS
(
	ID
)
GO

CREATE UNIQUE NONCLUSTERED INDEX UX_CONCURRENCY_TESTS_GUID
ON CONCURRENCY_TESTS
(
	GUID
)
GO