CREATE TABLE INTEGRATION_TESTS
(
	ID				INT								  NOT NULL IDENTITY(1,1),
	GUID			UNIQUEIDENTIFIER				  NOT NULL,
	VERSION			INT					DEFAULT(0)	  NOT NULL,
	CREATED_AT		DATETIME			DEFAULT(0)	  NOT NULL,
	UPDATED_AT		DATETIME			DEFAULT(0)	  NOT NULL,
	NAME			VARCHAR(128)					  NOT NULL,
	CONSTRAINT PK_INTEGRATION_TESTS PRIMARY KEY NONCLUSTERED (GUID)
)
GO

CREATE UNIQUE CLUSTERED INDEX UX_INTEGRATION_TESTS_ID
ON INTEGRATION_TESTS
(
	ID
)
GO

CREATE UNIQUE NONCLUSTERED INDEX UX_INTEGRATION_TESTS_GUID
ON INTEGRATION_TESTS
(
	GUID
)
GO